[package]
name = "rust_utilities"
authors = ["MedzikUser <nivua1fn@duck.com>"]
version = "0.1.0"
edition = "2021"

[features]
default = ["full"]

full = ["crypto", "sha"]
crypto = []
sha = ["sha-1", "sha2", "hex"]

# crypto
[dependencies.sha-1]
version = "0.10.0"
optional = true
[dependencies.sha2]
version = "0.10.2"
optional = true
[dependencies.hex]
version = "0.4.3"
optional = true
